clc;
disp('Welcome!');
disp('Restoring default path');
restoredefaultpath;

packages_dir = {...
    'acq/dtd', ...
    'acq/qmas', ...
    'mdm', ...
    'mio', ...
    'msf', ...
    'models/dti_nls',...
    'models/quick_dti',...
    };

addpath(pwd, '-end');

for c_package = 1:numel(packages_dir)
    addpath(fullfile(pwd, packages_dir{c_package}));
end

disp (char(10))
disp 'Done configuring paths for framework!'

