function setup_paths()
% function setup_paths()
%
% Restores the default paths and adds all relevant subdirs to the
% path. Run this when you start MATLAB to use the code.

clc;
disp('Welcome!');
disp('Restoring default path');
restoredefaultpath;

packages_dir = {...
    'acq/dtd', ...
    'acq/qmas', ...
    'acq/uvec', ...
    'man', ...
    'mdm', ...
    'mio', ...
    'mio/elastix', ...
    'msf', ...
    'models/dti_nls',...
    'models/vasco16',...
    'models/fexi11',...
    'models/quick_dti',...
    'models/dti_euler',...
    'models/axsym_pa',...
    };


t = fileparts(mfilename('fullpath'));

for c_package = 1:numel(packages_dir)
    addpath(fullfile(t, packages_dir{c_package}), '-end');
end

disp (char(10))
disp 'Done configuring paths for framework!'

