function res = bruker_mkshapefile_PV360(out_fn,g,tau,C,title_str)
% function res = bruker_mkshapefile(out_fn,g,title_str)

if nargin < 3
    title_str = 'Gradient shape generated by Matlab';
end

[out_path,~,~] = fileparts(out_fn);
if ~isfolder(out_path)
    mkdir(out_path)
end

fid = fopen(out_fn,'w');

text.header = {
{['##TITLE= ' title_str]};
{'##JCAMP-DX= 5.00 Bruker JCAMP library'}
{'##DATA TYPE= Shape Data'}
{'##ORIGIN= Bruker Analytik GmbH'}
{'##OWNER= <nmrsu>'}
{['##DATE= ' datestr(now,'yyyy-mm-dd')]}
{['##TIME= ' datestr(now,'HH:MM:SS')]}
{'##MINX= 0'}
{'##MAXX= 1'}
{'##MINY= 0'}
{'##MAXY= 1'}
{'##$SHAPE_EXMODE= Gradient'}
{'##$SHAPE_TOTROT= 0'}
{'##$SHAPE_BWFAC= 0'}
{'##$SHAPE_INTEGFAC= 0'}
{'##$SHAPE_MODE= 0'}};

[nlines, ~] = size(text.header);

for nline = 1:nlines
    fprintf(fid,'%s\n',text.header{nline}{1});
end
fprintf(fid,'%s\n',['##EFFIFACTOR=' num2str(C)]);
fprintf(fid,'%s\n',['##DURATION=' num2str(tau)]);
fprintf(fid,'%s\n','##DIRECTIONVEC= 0 0 1');
fprintf(fid,'%s\n',['##NPOINTS=' num2str(size(g,1))]);
fprintf(fid,'%s\n','##XYDATA= (X Y Z)');

formatspec = '%8.6f %8.6f %8.6f\r\n';
for ng = 1:size(g,1)
    fprintf(fid,formatspec,g(ng,:));
end

fprintf(fid,'%s\n','##END');
fclose(fid);

res = 1;