function fn = ut_dtd_gamma(c_ut)
% function fn = ut_dtd_gamma(c_ut)
%
% if c_ut is not supplied, the function returns the number of unit tests

% n_ut = number of unit tests
n_ut = 1;

if (nargin < 1)
    fn = n_ut;
    return;
end

switch c_ut
    
    case 1 % UT of a simple LTE, STE and PTE fitting where STE and LTE have
           % 20% higher and 10% lower baseline signal, respectively.
           
        fn  = 'dtd_gamma_1d_data2fit';
        opt = dtd_gamma_opt;
        
        tissue      = [100 .9e-9 0.41e-18 0.8e-18 1.2 0.9];
        
        xps.b = 1e9 * [0 1 2 3 0 1 2 3   0   1   2]';
        xps.b_delta = [1 1 1 1 0 0 0 0 -.5 -.5 -.5]';
        xps.b_eta   = [0 0 0 0 0 0 0 0   0   0   0]';
        xps.s_ind   = [1 1 1 1 2 2 2 2   3   3   3]';
        xps.n       = numel(xps.b);
        xps.pa_w    = 1;
        
        % Signal generated by running dtd_gamma_1d_fit2data(tissue, xps)
        signal      = [100 56.53 41.74 33.90 ... % STE
                       120 57.16 33.38 21.88 ... % LTE
                        90 45.27 28.85]';        % PTE
        
        t = dtd_gamma_1d_data2fit(signal, xps, opt);
        
        E = (t-tissue)./tissue;
        
        if any(abs(E) > 0.001) % 0.1% threshold
            error('Fit does not find the true values');
        end
        
        
    otherwise
        error(['This test (' num2str(c_ut) ') is not defined!'])
end
