function msf_clf(c_figure)

if (nargin == 0), c_figure = gcf; end

figure(c_figure);
clf;
set(gcf, ...
    'color','white', ...
    'defaultlinelinewidth', 2, ...
    'defaultaxeslinewidth', 2, ...
    'defaultaxesfontweight', 'bold', ...
    'defaultaxestickdir', 'out', ...
    'defaultaxesbox', 'off');


