function EG = mgui_analysis_setup_gui(EG, h)
% function EG = mgui_roi_setup_gui(EG, h)


left = 0.15;
width = 0.75;

EG.handles.h_analysis_top_axes = axes(...
    'parent', h, ...
    'units', 'normalized', ...
    'position', [left 0.5 width 0.3], ...
    'fontsize', EG.conf.default_font_size);

axis off;


EG.handles.h_analysis_bottom_axes = axes(...
    'parent', h, ...
    'units', 'normalized', ...
    'position', [left 0.1 width 0.3], ...
    'fontsize', EG.conf.default_font_size);

axis off;



left   = 10; 
bottom = 664;
width  = 100;
height = 15;


EG.handles.h_analysis_popup = uicontrol('style','popupmenu', ...
    'parent', h, ...
    'units', 'pixels', ...
    'position', [left bottom width height], ...
    'string', 'hello', ...
    'tag', EG.t_ANALYSIS_POPUP, ...
    'callback', @mgui_roi_gui_callback);


1;
